name: Build and run tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: node:16-alpine
    steps:
      - uses: actions/checkout@v3
      - name: test
        run: |
          npm ci
          npm run test

  lint:
    runs-on: ubuntu-latest
    container:
      image: node:16-alpine
    steps:
      - uses: actions/checkout@v3
      - name: lint
        run: |
          npm ci
          npm run lint:check
